import{a as S,S as v,i as n}from"./assets/vendor-CrlV4O_2.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function c(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const q="https://pixabay.com/api/",b="50642644-0750554656ca13a90436600ee";async function m(r,t=1){const o={key:b,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};return(await S.get(q,{params:o})).data}const g=document.querySelector(".gallery"),f=document.querySelector(".loader"),y=document.querySelector(".load-more"),B=new v(".gallery a");function h(r){const t=r.map(o=>`
    <li class="gallery-item">
      <a href="${o.largeImageURL}">
        <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy" />
      </a>
      <div class="info">
        <p><strong>Likes:</strong> ${o.likes}</p>
        <p><strong>Views:</strong> ${o.views}</p>
        <p><strong>Comments:</strong> ${o.comments}</p>
        <p><strong>Downloads:</strong> ${o.downloads}</p>
      </div>
    </li>`).join("");g.insertAdjacentHTML("beforeend",t),B.refresh()}function $(){g.innerHTML=""}function p(){f.classList.remove("is-hidden")}function L(){f.classList.add("is-hidden")}function M(){y.classList.remove("is-hidden")}function w(){y.classList.add("is-hidden")}const d=document.querySelector(".form"),P=document.querySelector(".load-more");let a="",i=1,u=0;d.addEventListener("submit",async r=>{if(r.preventDefault(),a=d.elements["search-text"].value.trim(),!a){n.warning({message:"Please enter a search query!"});return}$(),w(),i=1,p();try{const t=await m(a,i);if(u=t.totalHits,t.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}h(t.hits),u>15&&M()}catch{n.error({message:"Something went wrong. Try again later."})}finally{L(),d.reset()}});P.addEventListener("click",async()=>{i++,p();try{const r=await m(a,i);h(r.hits),I(),document.querySelectorAll(".gallery-item").length>=u&&(w(),n.info({message:"We're sorry, but you've reached the end of search results."}))}catch{n.error({message:"Something went wrong. Try again later."})}finally{L()}});function I(){const{height:r}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
